name: eazy_notification
description: Flutter Eazy notifications multiplatform
version: 0.0.1
homepage: https://github.com/bruc3balo/eazy_notification.git
platforms:
  android:
  ios:
  macos:
  windows:
  web:
  linux:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mplatform: ^0.0.2
  awesome_notifications: ^0.8.2
  local_notifier: ^0.1.5
  elegant_notification: ^1.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
